package bridge

import "github.com/GhostFlying/ferry/go/mobile/contract"

// ValidateConfigJSON is exported for the Android bridge generated by
// gomobile. JSON keeps platform-owned URI and lifecycle types out of Go.
func ValidateConfigJSON(input string) string { return contract.ValidateConfigJSON(input) }

// PlanJSON evaluates deterministic rules without opening a source URI.
func PlanJSON(input string) string { return contract.PlanJSON(input) }
